apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-site
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: www-site
  template:
    metadata:
      labels:
        app: www-site
    spec:
      containers:
      - name: www-site
        image: italomarcelo/lamp8:v1
        ports:
        - containerPort: 80 # porta do serviço (targetport)