apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
          # não fazer isso em produção 
            # - name: PMA_HOST
            #   value: db
            # - name: PMA_PORT
            #   value: "3306"
            # - name: MYSQL_ROOT_PASSWORD
            #   value: test 
            # utilizando secrets
            - name: PMA_HOST
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: database
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password
# ---